# Generated by Django 5.1

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('admissions', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Pricing amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('effective_from', models.DateField(help_text='Price effective from date')),
                ('effective_to', models.DateField(blank=True, help_text='Price effective to date (null = ongoing)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this pricing active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this pricing belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='subscriptions.organization')),
            ],
            options={
                'verbose_name': 'pricing',
                'verbose_name_plural': 'pricings',
                'db_table': 'pricings',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Payment plan name', max_length=100)),
                ('type', models.CharField(choices=[('MONTHLY', 'Monthly Installments'), ('FULL', 'Full Payment'), ('CUSTOM', 'Custom Plan')], default='MONTHLY', help_text='Payment plan type', max_length=20)),
                ('installment_count', models.IntegerField(blank=True, help_text='Number of installments (null for full payment)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage for this plan', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Is this plan active?')),
                ('description', models.TextField(blank=True, help_text='Plan description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this payment plan belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='subscriptions.organization')),
            ],
            options={
                'verbose_name': 'payment plan',
                'verbose_name_plural': 'payment plans',
                'db_table': 'payment_plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Discount name', max_length=100)),
                ('type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount')], default='PERCENTAGE', help_text='Discount type', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value (percentage or fixed amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('applicable_to', models.CharField(choices=[('FULL_PAYMENT', 'Full Payment'), ('SIBLING', 'Sibling Discount'), ('CUSTOM', 'Custom')], default='CUSTOM', help_text='Discount applicable to', max_length=20)),
                ('code', models.CharField(blank=True, help_text='Discount code (for future promo codes)', max_length=50, null=True, unique=True)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum purchase amount for discount', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (cap)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True, help_text='Is this discount active?')),
                ('valid_from', models.DateTimeField(help_text='Discount valid from')),
                ('valid_to', models.DateTimeField(blank=True, help_text='Discount valid to (null = ongoing)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this discount belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='subscriptions.organization')),
            ],
            options={
                'verbose_name': 'discount',
                'verbose_name_plural': 'discounts',
                'db_table': 'discounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before discounts', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount due', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Invoice status', max_length=20)),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('issued_at', models.DateTimeField(blank=True, help_text='Invoice issued date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(help_text='Enrollment this invoice is for', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='admissions.enrollment')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this invoice belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscriptions.organization')),
                ('payment_plan', models.ForeignKey(help_text='Payment plan for this invoice', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='payments.paymentplan')),
                ('pricing', models.ForeignKey(help_text='Pricing used for this invoice', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='payments.pricing')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(help_text='Unique payment number', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('payment_method', models.CharField(choices=[('MANUAL', 'Manual Entry'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('CHECK', 'Check'), ('OTHER', 'Other')], default='MANUAL', help_text='Payment method', max_length=20)),
                ('payment_gateway', models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('SQUARE', 'Square'), ('OTHER', 'Other')], help_text='Payment gateway (for e-commerce)', max_length=20, null=True)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Gateway transaction ID (for e-commerce)', max_length=200, null=True)),
                ('gateway_response', models.JSONField(blank=True, help_text='Gateway response data (for e-commerce)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Payment status', max_length=20)),
                ('payment_date', models.DateTimeField(help_text='Payment date')),
                ('receipt_number', models.CharField(blank=True, help_text='Receipt number', max_length=50, null=True, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Refund amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('refund_reason', models.TextField(blank=True, help_text='Refund reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(help_text='Invoice this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.invoice')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this payment belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.organization')),
                ('recorded_by', models.ForeignKey(help_text='Admin who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student who made the payment', limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(help_text='Scheduled payment date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Scheduled payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('SKIPPED', 'Skipped')], default='PENDING', help_text='Schedule status', max_length=20)),
                ('late_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Late fee applied', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(help_text='Invoice this schedule item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='payments.invoice')),
                ('paid_payment', models.ForeignKey(blank=True, help_text='Payment that fulfilled this schedule item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_schedules', to='payments.payment')),
            ],
            options={
                'verbose_name': 'payment schedule',
                'verbose_name_plural': 'payment schedules',
                'db_table': 'payment_schedules',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Payment method name', max_length=100)),
                ('code', models.CharField(help_text='Payment method code', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is this payment method active?')),
                ('requires_receipt', models.BooleanField(default=False, help_text='Does this payment method require a receipt?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this payment method belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='subscriptions.organization')),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
                'db_table': 'payment_methods',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='pricing',
            index=models.Index(fields=['organization'], name='pricings_organiz_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='pricing',
            index=models.Index(fields=['content_type', 'object_id'], name='pricings_content_789012_idx'),
        ),
        migrations.AddIndex(
            model_name='pricing',
            index=models.Index(fields=['effective_from', 'effective_to'], name='pricings_effectiv_345678_idx'),
        ),
        migrations.AddIndex(
            model_name='pricing',
            index=models.Index(fields=['is_active'], name='pricings_is_acti_901234_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentplan',
            index=models.Index(fields=['organization'], name='payment_plan_organiz_567890_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentplan',
            index=models.Index(fields=['type'], name='payment_plan_type_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentplan',
            index=models.Index(fields=['is_active'], name='payment_plan_is_acti_789012_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['organization'], name='discounts_organiz_345678_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['code'], name='discounts_code_901234_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['is_active'], name='discounts_is_acti_567890_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['valid_from', 'valid_to'], name='discounts_valid_f_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization'], name='invoices_organiz_789012_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['enrollment'], name='invoices_enroll_345678_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_invoic_901234_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_status_567890_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoices_due_dat_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization'], name='payments_organiz_789012_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='payments_invoic_345678_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student'], name='payments_student_901234_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='payments_paymen_567890_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_paymen_789012_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_transaction_id'], name='payments_gatewa_345678_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['invoice'], name='payment_sch_invoic_901234_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['scheduled_date'], name='payment_sch_schedu_567890_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentschedule',
            index=models.Index(fields=['status'], name='payment_sch_status_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['organization'], name='payment_met_organiz_789012_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['is_active'], name='payment_met_is_acti_345678_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricing',
            constraint=models.UniqueConstraint(fields=['content_type', 'object_id', 'effective_from'], name='pricings_unique_pricing'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=['organization', 'code'], name='payment_methods_unique_org_code'),
        ),
    ]

