# Generated by Django 5.1 on 2025-11-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("payments", "0001_initial"),
        (
            "subscriptions",
            "0002_rename_billings_organization_idx_billings_organiz_190951_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="paymentmethod",
            name="payment_methods_unique_org_code",
        ),
        migrations.RemoveConstraint(
            model_name="pricing",
            name="pricings_unique_pricing",
        ),
        migrations.RenameIndex(
            model_name="discount",
            new_name="discounts_organiz_5ea1c8_idx",
            old_name="discounts_organiz_345678_idx",
        ),
        migrations.RenameIndex(
            model_name="discount",
            new_name="discounts_code_74af5d_idx",
            old_name="discounts_code_901234_idx",
        ),
        migrations.RenameIndex(
            model_name="discount",
            new_name="discounts_is_acti_49deb3_idx",
            old_name="discounts_is_acti_567890_idx",
        ),
        migrations.RenameIndex(
            model_name="discount",
            new_name="discounts_valid_f_3e5347_idx",
            old_name="discounts_valid_f_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoices_organiz_d296b0_idx",
            old_name="invoices_organiz_789012_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoices_enrollm_2c58dd_idx",
            old_name="invoices_enroll_345678_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoices_invoice_7778bc_idx",
            old_name="invoices_invoic_901234_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoices_status_07776b_idx",
            old_name="invoices_status_567890_idx",
        ),
        migrations.RenameIndex(
            model_name="invoice",
            new_name="invoices_due_dat_039a25_idx",
            old_name="invoices_due_dat_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_organiz_eee556_idx",
            old_name="payments_organiz_789012_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_invoice_9dd568_idx",
            old_name="payments_invoic_345678_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_student_5b85b3_idx",
            old_name="payments_student_901234_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_payment_c27a96_idx",
            old_name="payments_paymen_567890_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_status_d621e5_idx",
            old_name="payments_status_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_payment_aebcb7_idx",
            old_name="payments_paymen_789012_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_gateway_f512b1_idx",
            old_name="payments_gatewa_345678_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentmethod",
            new_name="payment_met_organiz_56c716_idx",
            old_name="payment_met_organiz_789012_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentmethod",
            new_name="payment_met_is_acti_395fa6_idx",
            old_name="payment_met_is_acti_345678_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentplan",
            new_name="payment_pla_organiz_ab29d3_idx",
            old_name="payment_plan_organiz_567890_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentplan",
            new_name="payment_pla_type_e624b1_idx",
            old_name="payment_plan_type_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentplan",
            new_name="payment_pla_is_acti_57c695_idx",
            old_name="payment_plan_is_acti_789012_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentschedule",
            new_name="payment_sch_invoice_343f46_idx",
            old_name="payment_sch_invoic_901234_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentschedule",
            new_name="payment_sch_schedul_7e616b_idx",
            old_name="payment_sch_schedu_567890_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentschedule",
            new_name="payment_sch_status_8f4549_idx",
            old_name="payment_sch_status_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="pricing",
            new_name="pricings_organiz_c6d3ad_idx",
            old_name="pricings_organiz_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="pricing",
            new_name="pricings_content_f3ed8b_idx",
            old_name="pricings_content_789012_idx",
        ),
        migrations.RenameIndex(
            model_name="pricing",
            new_name="pricings_effecti_5dcdb5_idx",
            old_name="pricings_effectiv_345678_idx",
        ),
        migrations.RenameIndex(
            model_name="pricing",
            new_name="pricings_is_acti_1f0299_idx",
            old_name="pricings_is_acti_901234_idx",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_gateway",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MANUAL", "Manual"),
                    ("STRIPE", "Stripe"),
                    ("PAYPAL", "PayPal"),
                    ("SQUARE", "Square"),
                    ("OTHER", "Other"),
                ],
                default="MANUAL",
                help_text="Payment gateway (for e-commerce)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentmethod",
            unique_together={("organization", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="pricing",
            unique_together={("content_type", "object_id", "effective_from")},
        ),
    ]
