# Generated by Django 5.1 on 2025-12-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_paymentmethod_payment_methods_unique_org_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether invoice email has been sent'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When invoice email was sent', null=True),
        ),
    ]
