# Generated by Django 5.1 on 2025-12-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="fileactivity",
            new_name="storage_fil_file_id_8bc671_idx",
            old_name="storage_fi_file_id_4b22a8_idx",
        ),
        migrations.RenameIndex(
            model_name="fileactivity",
            new_name="storage_fil_user_id_202d6e_idx",
            old_name="storage_fi_user_id_c8b42e_idx",
        ),
        migrations.RenameIndex(
            model_name="fileactivity",
            new_name="storage_fil_action_8f6b9a_idx",
            old_name="storage_fi_action__343d1a_idx",
        ),
        migrations.RenameIndex(
            model_name="fileobject",
            new_name="storage_fil_organiz_52ae26_idx",
            old_name="storage_fi_organiz_0ef19b_idx",
        ),
        migrations.RenameIndex(
            model_name="fileobject",
            new_name="storage_fil_owner_t_b5d648_idx",
            old_name="storage_fi_owner_t_f8e7ff_idx",
        ),
        migrations.RenameIndex(
            model_name="fileobject",
            new_name="storage_fil_is_arch_cdc138_idx",
            old_name="storage_fi_is_arch_d9c69c_idx",
        ),
        migrations.AddField(
            model_name="fileobject",
            name="cloudinary_folder",
            field=models.CharField(
                blank=True, help_text="Cloudinary folder path", max_length=512
            ),
        ),
        migrations.AddField(
            model_name="fileobject",
            name="cloudinary_public_id",
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
        migrations.AddField(
            model_name="fileobject",
            name="cloudinary_resource_type",
            field=models.CharField(
                blank=True,
                default="image",
                help_text="Resource type: image, video, or raw",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fileobject",
            name="cloudinary_url",
            field=models.CharField(
                blank=True, help_text="Direct URL to the file", max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name="fileobject",
            name="drive_file_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fileobject",
            name="drive_folder_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="fileobject",
            name="logical_path",
            field=models.CharField(
                blank=True,
                help_text="Logical path inside storage, e.g. gallery/user-123",
                max_length=512,
            ),
        ),
    ]
