# Generated by Django 5.1 on 2025-11-05 23:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('EXAM', 'Exam'), ('QUIZ', 'Quiz'), ('PROJECT', 'Project')], default='QUIZ', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('due_at', models.DateTimeField(help_text='Due date and time')),
                ('published', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='catalog.cohort')),
            ],
            options={
                'verbose_name': 'assessment',
                'verbose_name_plural': 'assessments',
                'db_table': 'assessments',
                'ordering': ['-due_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, help_text='Student score', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_score', models.DecimalField(decimal_places=2, default=100, help_text='Maximum possible score', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessment.assessment')),
                ('graded_by', models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'LECTURER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_assessments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('late_flag', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessment.assessment')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'submission',
                'verbose_name_plural': 'submissions',
                'db_table': 'submissions',
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['cohort'], name='assessments_cohort__cf68a5_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['due_at'], name='assessments_due_at_e79d05_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['published'], name='assessments_publish_e47898_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['assessment'], name='grades_assessm_ff72b1_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student'], name='grades_student_b8b331_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['graded_at'], name='grades_graded__013052_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('assessment', 'student')},
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assessment'], name='submissions_assessm_8cd3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student'], name='submissions_student_51a963_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['submitted_at'], name='submissions_submitt_9b96b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assessment', 'student')},
        ),
    ]
