# Generated by Django 5.1 on 2025-11-14 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
        ("catalog", "0002_cohort_organization_course_organization_and_more"),
        ("subscriptions", "0001_initial"),  # Depend on initial, not 0002
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this assessment belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="subscriptions.organization",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this grade belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="subscriptions.organization",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this submission belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="subscriptions.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["organization"], name="assessments_organiz_63b33d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["organization"], name="grades_organiz_400fa3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["organization"], name="submissions_organiz_cf87b9_idx"
            ),
        ),
    ]
