# Generated by Django 5.1 on 2025-11-05 23:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('schedule_pref', models.CharField(blank=True, help_text='Schedule preference', max_length=100)),
                ('experience_level', models.CharField(blank=True, help_text='Experience level', max_length=50)),
                ('referral_source', models.CharField(blank=True, help_text='How did you hear about us?', max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('consent_ts', models.DateTimeField(auto_now_add=True, help_text='Consent timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='catalog.program')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'db_table': 'applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='application_status_e61111_idx'), models.Index(fields=['program'], name='application_program_e087fd_idx'), models.Index(fields=['email'], name='application_email_7bef0d_idx'), models.Index(fields=['created_at'], name='application_created_a07231_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='catalog.cohort')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollments',
                'db_table': 'enrollments',
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['student'], name='enrollments_student_379f04_idx'), models.Index(fields=['cohort'], name='enrollments_cohort__3fdafd_idx'), models.Index(fields=['status'], name='enrollments_status_dfab18_idx'), models.Index(fields=['enrolled_at'], name='enrollments_enrolle_00c691_idx')],
                'unique_together': {('student', 'cohort')},
            },
        ),
    ]
