# Generated by Django 5.1 on 2025-11-27 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_enrollment_enrollments_student_929bef_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Contact name or relation, e.g. "Mother", "Father", "Guardian"', max_length=255)),
                ('phone', models.CharField(help_text='Phone number for this contact', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(help_text='Application this phone number belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='admissions.application')),
            ],
            options={
                'verbose_name': 'application phone',
                'verbose_name_plural': 'application phones',
                'db_table': 'application_phones',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['application'], name='application_applica_30c483_idx'), models.Index(fields=['phone'], name='application_phone_88a76e_idx')],
            },
        ),
    ]
