# Generated by Django 5.1 on 2025-12-20 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_applicationphone'),
        ('catalog', '0004_cohort_min_enrollment_alter_cohort_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='preferred_course',
            field=models.ForeignKey(blank=True, help_text='Preferred course (can be changed by admin before cohort starts)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_enrollments', to='catalog.course'),
        ),
    ]
