# Generated by Django 5.1 on 2025-11-14 15:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_cohort_organization_course_organization_and_more"),
        (
            "subscriptions",
            "0002_rename_billings_organization_idx_billings_organiz_190951_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "per_hour_minor",
                    models.BigIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this rate belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="subscriptions.organization",
                    ),
                ),
            ],
            options={
                "db_table": "tk_rates",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="tk_rates_organiz_ca297b_idx"
                    ),
                    models.Index(
                        fields=["lecturer", "active"],
                        name="tk_rates_lecture_8090c2_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("lecturer",),
                        name="tk_one_active_rate_per_lecturer",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("total_minutes", models.PositiveIntegerField(default=0)),
                ("amount_minor", models.BigIntegerField(default=0)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this timesheet belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="subscriptions.organization",
                    ),
                ),
            ],
            options={
                "db_table": "tk_timesheets",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="tk_timeshee_organiz_19b8d4_idx"
                    ),
                    models.Index(
                        fields=["lecturer", "period_start", "period_end"],
                        name="tk_timeshee_lecture_891bf3_idx",
                    ),
                ],
                "unique_together": {("lecturer", "period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="WorkLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "minutes",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SESSION", "From session"),
                            ("MANUAL", "Manual entry"),
                        ],
                        default="SESSION",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worklogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this worklog belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worklogs",
                        to="subscriptions.organization",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worklogs",
                        to="catalog.session",
                    ),
                ),
            ],
            options={
                "db_table": "tk_worklogs",
                "ordering": ["-start_at"],
                "indexes": [
                    models.Index(
                        fields=["organization"], name="tk_worklogs_organiz_a2ce54_idx"
                    ),
                    models.Index(
                        fields=["lecturer", "start_at"],
                        name="tk_worklogs_lecture_f6ac6a_idx",
                    ),
                    models.Index(
                        fields=["session"], name="tk_worklogs_session_54f2e0_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_at__gt", models.F("start_at"))),
                        name="tk_worklog_valid_range",
                    )
                ],
            },
        ),
    ]
