# Generated by Django 5.1 on 2025-11-05 23:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial', models.CharField(db_index=True, help_text='Certificate serial number', max_length=100, unique=True)),
                ('qr_token', models.CharField(db_index=True, help_text='QR code verification token', max_length=64, unique=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='certificates/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('REVOKED', 'Revoked')], default='ISSUED', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='catalog.cohort')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['student'], name='certificate_student_e19697_idx'), models.Index(fields=['cohort'], name='certificate_cohort__602879_idx'), models.Index(fields=['serial'], name='certificate_serial_ee9062_idx'), models.Index(fields=['qr_token'], name='certificate_qr_toke_6a9e3c_idx'), models.Index(fields=['status'], name='certificate_status_a01db5_idx')],
            },
        ),
    ]
