# Generated by Django 5.1 on 2025-11-14 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add organization field to User model.
    
    IMPORTANT: This migration must run AFTER subscriptions.0001_initial
    to ensure Organization table exists before adding the ForeignKey.
    """

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("subscriptions", "0001_initial"),  # Must run after Organization table is created
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="subscriptions.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["organization"], name="users_organiz_ca9165_idx"
            ),
        ),
    ]
