# Generated by Django 5.1 on 2025-12-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_mfa_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.CharField(
                blank=True,
                help_text="Cloudinary public_id for profile picture",
                max_length=512,
                null=True,
            ),
        ),
    ]
