# Generated by Django 5.1 on 2025-11-05 23:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('CONSENT', 'Consent Form'), ('ID', 'ID Document'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('ADMIN', 'Admin Only'), ('LECTURER', 'Lecturer Visible')], default='PRIVATE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner'], name='documents_owner_i_3fe723_idx'), models.Index(fields=['kind'], name='documents_kind_440c76_idx')],
            },
        ),
    ]
