# Generated by Django 5.1 on 2025-11-14 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
        ("subscriptions", "0001_initial"),  # Depend on initial, not 0002
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this document belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="subscriptions.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["organization"], name="documents_organiz_5acdbc_idx"
            ),
        ),
    ]
