# Generated by Django 5.1 on 2025-12-11 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_file_object"),
        (
            "storage",
            "0002_rename_storage_fi_file_id_4b22a8_idx_storage_fil_file_id_8bc671_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_object",
            field=models.ForeignKey(
                blank=True,
                help_text="Backed file object in Cloudinary or other storage",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="storage.fileobject",
            ),
        ),
    ]
