# Generated by Django 5.1 on 2025-11-14 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="billing",
            new_name="billings_organiz_190951_idx",
            old_name="billings_organization_idx",
        ),
        migrations.RenameIndex(
            model_name="billing",
            new_name="billings_status_fc38e8_idx",
            old_name="billings_status_idx",
        ),
        migrations.RenameIndex(
            model_name="billing",
            new_name="billings_due_dat_91bb2d_idx",
            old_name="billings_due_date_idx",
        ),
        migrations.RenameIndex(
            model_name="organization",
            new_name="organizatio_domain_edc3a8_idx",
            old_name="organizations_domain_idx",
        ),
        migrations.RenameIndex(
            model_name="organization",
            new_name="organizatio_status_195db0_idx",
            old_name="organizations_status_idx",
        ),
        migrations.RenameIndex(
            model_name="planfeature",
            new_name="plan_featur_plan_id_622759_idx",
            old_name="plan_features_plan_module_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_organiz_5780cf_idx",
            old_name="subscriptions_organization_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_status_572d44_idx",
            old_name="subscriptions_status_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_end_dat_763002_idx",
            old_name="subscriptions_end_date_idx",
        ),
        migrations.AlterField(
            model_name="billing",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Billing amount",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monthly price",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
