# Generated by Django 5.1 on 2025-11-05 23:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Course code', max_length=50)),
                ('hours', models.IntegerField(help_text='Total course hours', validators=[django.core.validators.MinValueValidator(1)])),
                ('credits', models.IntegerField(blank=True, help_text='Course credits', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('syllabus_version', models.CharField(default='1.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Cohort name', max_length=200)),
                ('capacity', models.IntegerField(help_text='Maximum number of students', validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField(help_text='Cohort start date')),
                ('end_date', models.DateField(help_text='Cohort end date')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ENROLLING', 'Enrolling'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(blank=True, limit_choices_to={'role': 'LECTURER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohorts', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='catalog.course')),
            ],
            options={
                'verbose_name': 'cohort',
                'verbose_name_plural': 'cohorts',
                'db_table': 'cohorts',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Program name', max_length=200)),
                ('code', models.CharField(help_text='Program code', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', help_text='Program version', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'db_table': 'programs',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='programs_code_a0c867_idx'), models.Index(fields=['active'], name='programs_active_bfdbaa_idx')],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='catalog.program'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(help_text='Session start time')),
                ('end_at', models.DateTimeField(help_text='Session end time')),
                ('location', models.CharField(blank=True, help_text='Physical location', max_length=200)),
                ('online_link', models.URLField(blank=True, help_text='Online meeting link')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='catalog.cohort')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'db_table': 'sessions',
                'ordering': ['start_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['course'], name='cohorts_course__9250a6_idx'),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['lecturer'], name='cohorts_lecture_bd67e7_idx'),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['status'], name='cohorts_status_5864a7_idx'),
        ),
        migrations.AddIndex(
            model_name='cohort',
            index=models.Index(fields=['start_date', 'end_date'], name='cohorts_start_d_58d40b_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['program'], name='courses_program_4589bd_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='courses_code_fa42f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('program', 'code')},
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['cohort'], name='sessions_cohort__80666e_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['start_at'], name='sessions_start_a_e7a732_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_cancelled'], name='sessions_is_canc_69a84b_idx'),
        ),
    ]
