# Generated by Django 5.1 on 2025-11-14 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("subscriptions", "0001_initial"),  # Depend on initial, not 0002
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this cohort belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cohorts",
                to="subscriptions.organization",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this course belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="subscriptions.organization",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this program belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="subscriptions.organization",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this session belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="subscriptions.organization",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="code",
            field=models.CharField(help_text="Program code", max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="program",
            unique_together={("organization", "code")},
        ),
        migrations.AddIndex(
            model_name="cohort",
            index=models.Index(
                fields=["organization"], name="cohorts_organiz_9129c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["organization"], name="courses_organiz_dfe9a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(
                fields=["organization"], name="programs_organiz_1c62f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["organization"], name="sessions_organiz_ddc4fe_idx"
            ),
        ),
    ]
