# Generated by Django 5.1 on 2025-11-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_cohort_organization_course_organization_and_more"),
        (
            "subscriptions",
            "0002_rename_billings_organization_idx_billings_organiz_190951_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["cohort", "start_at"], name="sessions_cohort__92090a_idx"
            ),
        ),
    ]
