# Generated by Django 5.1 on 2025-12-20 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_session_sessions_cohort__92090a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='min_enrollment',
            field=models.IntegerField(default=8, help_text='Minimum number of students required to start', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='capacity',
            field=models.IntegerField(default=20, help_text='Maximum number of students', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
