# Generated by Django 5.1 on 2025-12-20 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_cohort_min_enrollment_alter_cohort_capacity'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether notification has been read'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='', help_text='Notification message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('COHORT_READY', 'Cohort Ready to Start'), ('INVOICE_CREATED', 'Invoice Created'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_OVERDUE', 'Payment Overdue'), ('OTHER', 'Other')], default='OTHER', help_text='Type of notification', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='When notification was read', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_cohort',
            field=models.ForeignKey(blank=True, help_text='Related cohort (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='catalog.cohort'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who receives this notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='notificatio_user_id_e78525_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
    ]
