# Generated by Django 5.1 on 2025-11-05 23:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], default='ABSENT', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'LECTURER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='catalog.session')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'attendance record',
                'verbose_name_plural': 'attendance records',
                'db_table': 'attendance_records',
                'indexes': [models.Index(fields=['session'], name='attendance__session_a40e0b_idx'), models.Index(fields=['student'], name='attendance__student_8ea8b5_idx'), models.Index(fields=['status'], name='attendance__status_5b1243_idx'), models.Index(fields=['marked_at'], name='attendance__marked__4ce7ce_idx')],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
