# Generated by Django 5.1 on 2025-11-14 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("catalog", "0002_cohort_organization_course_organization_and_more"),
        ("subscriptions", "0001_initial"),  # Depend on initial, not 0002
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this attendance record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="subscriptions.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["organization"], name="attendance__organiz_08010c_idx"
            ),
        ),
    ]
