# Generated by Django 5.1 on 2025-11-24 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendancerecord_organization_and_more"),
        ("catalog", "0002_cohort_organization_course_organization_and_more"),
        (
            "subscriptions",
            "0002_rename_billings_organization_idx_billings_organiz_190951_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(
                fields=["session", "student"], name="attendance__session_e37d63_idx"
            ),
        ),
    ]
